version: '3'
services:
  backend:
    build:
      context: /src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    container_name: mongo_container
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: